SET SERVEROUTPUT ON;
SET VERIFY OFF;
SET LINESIZE 1000;


SELECT * FROM Student1;
UNION
SELECT * FROM Student2@site1;

SELECT * FROM Enrollment1
UNION
SELECT * FROM Enrollment2@site1;

SELECT * FROM Teacher1
UNION
SELECT * FROM Teacher2@site1;